name: Build LaTeX document

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - uses: cvxgrp/.github/actions/latex@main
        with:
          paper: book.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
