name: Build LaTeX document

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - uses: cvxgrp/.github/actions/latex@main
        with:
          paper: markowitz.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Doesn't make sense at this stage. We miss now.clo and also all the plots
      #- uses: cvxgrp/.github/actions/latex@main
      #  with:
      #    paper: kahn_multiperiod_sourcecode/cvx_portfolio.tex
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
